####################################
# DATABASE
####################################

spring.datasource.url=jdbc:postgresql://localhost:5432/airesume_db

spring.datasource.username=postgres

spring.datasource.password=Bhawani$969460

spring.datasource.driver-class-name=org.postgresql.Driver

####################################
# JPA
####################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

####################################
# JWT
####################################

jwt.secret=N0aWCleV8UaeO03MZ0yMIsLpkjOQV557Dx+8MBPOQfQ=

jwt.access-token-expiration=900000

jwt.refresh-token-expiration=604800000

####################################
# MAIL
####################################

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=bhawanisingh.rcert@gmail.com

spring.mail.password=huubqdqwzzmjgate

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

####################################
# REDIS
####################################

spring.data.redis.host=localhost

spring.data.redis.port=6379



app:
file:
upload-dir: uploads/resumes